INSERT INTO C_HOME_TYPE (ID, DESCRIPTION) VALUES (1, 'Piso');
INSERT INTO C_HOME_TYPE (ID, DESCRIPTION) VALUES (2, 'Familiar');
INSERT INTO C_HOME_TYPE (ID, DESCRIPTION) VALUES (3, 'Habitación');
INSERT INTO C_HOME_TYPE (ID, DESCRIPTION) VALUES (4, 'Estudio');

-- TYPE_FAMILY
INSERT INTO C_FAMILY_TYPE (ID, DESCRIPTION) VALUES (1, 'Sola');
INSERT INTO C_FAMILY_TYPE (ID, DESCRIPTION) VALUES (2, 'Pareja con Hijos');
INSERT INTO C_FAMILY_TYPE (ID, DESCRIPTION) VALUES (3, 'Pareja sin Hijos');
INSERT INTO C_FAMILY_TYPE (ID, DESCRIPTION) VALUES (4, 'Monoparental');
INSERT INTO C_FAMILY_TYPE (ID, DESCRIPTION) VALUES (4, 'Otra');

INSERT INTO C_AUTHORIZATION_TYPE (ID, DESCRIPTION) VALUES (1, 'Autorización Residencia');
INSERT INTO C_AUTHORIZATION_TYPE (ID, DESCRIPTION) VALUES (2, 'Autorización Residencia y Trabajo');
INSERT INTO C_AUTHORIZATION_TYPE (ID, DESCRIPTION) VALUES (3, 'Estudios');
INSERT INTO C_AUTHORIZATION_TYPE (ID, DESCRIPTION) VALUES (4, 'Turismo');
INSERT INTO C_AUTHORIZATION_TYPE (ID, DESCRIPTION) VALUES (5, 'Refugiado');
INSERT INTO C_AUTHORIZATION_TYPE (ID, DESCRIPTION) VALUES (6, 'Indocumentado');
INSERT INTO C_AUTHORIZATION_TYPE (ID, DESCRIPTION) VALUES (7, 'Situación Administrativa Irregular');

INSERT INTO C_JOB_SITUATION (ID, DESCRIPTION) VALUES (1, 'Parado');
INSERT INTO C_JOB_SITUATION (ID, DESCRIPTION) VALUES (2, 'Con Trabajo Normalizado');
INSERT INTO C_JOB_SITUATION (ID, DESCRIPTION) VALUES (3, 'Con Trabajo Marginal o Economia Sumergida');
INSERT INTO C_JOB_SITUATION (ID, DESCRIPTION) VALUES (4, 'Labores del hogar (ama de casa)');
INSERT INTO C_JOB_SITUATION (ID, DESCRIPTION) VALUES (5, 'Pensionista o Jubilado');
INSERT INTO C_JOB_SITUATION (ID, DESCRIPTION) VALUES (6, 'Otros inactivos (estudiantes, menores');

INSERT INTO C_STUDIES (ID, DESCRIPTION) VALUES (1, 'No sabe leer ni escribir');
INSERT INTO C_STUDIES (ID, DESCRIPTION) VALUES (2, 'Sólo sabe leer y escribir');
INSERT INTO C_STUDIES (ID, DESCRIPTION) VALUES (3, 'Infanil');
INSERT INTO C_STUDIES (ID, DESCRIPTION) VALUES (4, 'Primaria');
INSERT INTO C_STUDIES (ID, DESCRIPTION) VALUES (5, 'Secundaria');
INSERT INTO C_STUDIES (ID, DESCRIPTION) VALUES (6, 'Bachillerato');
INSERT INTO C_STUDIES (ID, DESCRIPTION) VALUES (7, 'FP-Grado Medio');
INSERT INTO C_STUDIES (ID, DESCRIPTION) VALUES (8, 'FP-Grado Superior');
INSERT INTO C_STUDIES (ID, DESCRIPTION) VALUES (9, 'Universidad Diplomado');